proverbs_eng = [
    "Never spend your money before you have it.",
    "Money has no smell.",
    "If you’re saving, you’re succeeding.",
    "A penny saved is a penny earned.",
    "Frugality includes all the other virtues.",
    "Saving must become a priority, not just a thought. Pay yourself first.",
    "Enough is better than too much.",
    "Small amounts saved daily add up to huge investments in the end.",
    "The rich invest in time, the poor invest in money.",
    "Money is usually attracted, not pursued.",
    "Money is better than poverty, if only for financial reasons.",
    "Know what you own, and know why you own it.",
    "Greed is not a financial issue. It’s a heart issue.",
    "Life is a boomerang. What you give, you get.",
]

proverbs_kor = [
    "돈이 돈을 번다",
    "돈만 있으면 귀신도 부릴 수 있다",
    "부잣집은 망해도 삼 년을 간다",
    "강물도 쓰면 준다",
    "티끌 모아 태산",
    "소같이 벌어서 쥐같이 먹어라",
    "개같이 벌어서 정승같이 써라",
    "굶어 죽기는 정승하기 보다 어렵다",
    "돈은 더럽게 벌어도 깨끗이 쓰면 된다",
    "돈만 있으면 처녀 불알도 산다",
    "못 입어 잘난 놈 없고, 잘 입어 못난 놈 없다",
    "쌀독에서 인심난다",
    "단단한 땅에 물이 괸다",
    "가난하게 태어난 것은 당신 잘못이 아니다. 그러나 가난하게 죽는 것은 당신 잘못이다",
    "한 푼 아낀 것은 한 푼 번것이나 마찬가지다",
    "내일 할 일을 오늘 하고 오늘 먹을 것을 내일 먹어라",
    "수입을 생각하고 나서 지출 계획을 세워라",
    "돈 생각을 떨쳐내는 유일한 방법은 돈을 많이 갖는 것이다",
    "돈에 대해 쉽게 사는 방법은 생활 수준을 형편보다 한 단계 낮추는 것이다",
    "하.. 돈 벌기 힘들다 -김 찬"
]